name: Docker CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: windows-2019  # 選擇運行環境，這邊是使用 Windows 2019 版虛擬機，是.NET Framework 需求的運行環境，需與 Docker Image 使用相同 win 版本

    steps:
    - name: Checkout code  # 檢出代碼庫的內容，以便後續操作可以使用代碼
      uses: actions/checkout@v3

    - name: Build the Docker image  # --force-rm 映像建構完成後，立即刪除中間容器，以節省磁盤空間 # 加入需求的參數source # 根據 Dockerfile 的位置設置路徑
      run: |
        docker build --force-rm -t nf-db-lab ./NFDBLab

    - name: Run the container  # -P 將使用中的容器端口，映射到宿主機的隨機端口
      run: |
        docker run -P -d --name my-container nf-db-lab

    - name: Stop and remove the container
      run: |
        docker rm -f my-container
