name: Docker CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest  # 選擇運行環境

    steps:
    - name: Checkout code  # 檢出代碼庫的內容，以便後續操作可以使用代碼
      uses: actions/checkout@v3

    - name: Build the Docker image  # 根據 Dockerfile 的位置設置路徑
      run: |
        docker build -t nf-db-lab ./NFDBLab

    - name: Run the container
      run: |
        docker run -p 80:5000 -d --name my-container nf-db-lab 

    - name: Stop and remove the container
      run: |
        docker rm -f nf-db-lab
